INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('danshishi', 'King', 'Teddy', '2001-12-03', '2012-10-12');
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('kante', 'Solomon', 'Grundy', '1990-12-12', '1991-01-01');
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('folukotibo', 'Folusho', 'kotibo', '2001-01-01', null);
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('folukotibo', 'Folusho', 'kotibo', '2022-03-13', null);
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('folukotibo', 'Folusho', 'kotibo', '2022-03-13', null);
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('folukotibo', 'Folusho', 'kotibo', '2022-03-13', null);
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('folukotibo', 'Folusho', 'kotibo', '2022-03-13', null);
INSERT INTO users (username, first_name, last_name, created_at, updated_at) VALUES ('folukotibo', 'Folusho', 'kotibo', '2022-03-13', null);
INSERT INTO songs (id, user_id, name, genre, created_at, updated_at) VALUES (1, 3, '(So bad) Joe boy ft Simi', 'afro', '2021-03-14', null);
INSERT INTO songs (id, user_id, name, genre, created_at, updated_at) VALUES (3, 5, '(To the moon) Sam Topkins', 'hiphop', '2022-03-14', null);
INSERT INTO songs (id, user_id, name, genre, created_at, updated_at) VALUES (4, 5, '(Lie) Kizz Daniel', 'afro', '2022-01-18', null);